CREATE TABLE  IF NOT EXISTS user(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
First_Name VARCHAR(20) NOT NULL,
Last_Name VARCHAR(20) NOT NULL,
Email VARCHAR(35) NOT NULL,
Password VARCHAR(220) NOT NULL,
Image VARCHAR (255) DEFAULT 'https://static.thenounproject.com/png/2349575-200.png'
);

CREATE TABLE IF NOT EXISTS post(
PostId INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Text Text,
Created_On DATETIME,
Likes INT DEFAULT 0,
userId INT NOT NULL,
FOREIGN  KEY (userId) REFERENCES user(Id)
);
